[x] in run_etl.py there is absolute path defined solve it with conf
[ ] modularize the package's modules 
[ ] add the api_key to .env
[ ] timestamp sat as index but not saved because index=False solve this
[ ] Install pytest-cov
[ ] in to_sql add index="timestamp"